### ISSUE TITLE
Target mAP?

### ISSUE THREAD

**Issue by msarmiento3** [Siyu-C/ACAR-Net#8] opened 2021-06-08 18:08 UTC
Which is the map that this code achieves? I was expecting to get 27.83 as the paper says. However, I am only able to get a 27.1. I am using batch 4 with 8 GPUS (32 total) and 0.064 as warmup_lr. Am I missing something?

**Comment by Siyu-C** [comment] 2021-06-12 12:46
Hi @msarmiento3 . First, thank you for using our code!

About the drop in performance, the most possible reason is that setting batch size per GPU to be larger than 1 has negative effect on our method. This is because we pad zeros to input clips of the mini-batch within a GPU to make them have the same spatial sizes. This is similar to common object detection training, yet these zeros can potentially harm our high-order relation reasoning process. That is why in our own settings, we set the batch size to 1.

Besides the batch size factor, AVA training can also be sensitive to a list of other factors.
- PyTorch version. For example, it seems that 3D convolutions of torch 1.3 and >=1.5 gives slightly different outputs to the same input tensor.
- Backend used for distributed training.
- Details in data preprocessing, such as the version of ffmpeg.
Due to these uncertainties, I suppose getting an mAP within range ±0.5 is already a reasonable reproduction for training.

**Comment by Siyu-C** [comment] 2021-06-28 15:22
Closing this issue since no further problem is posed.

**Closed by Siyu-C** 2021-06-28 15:22 UTC

**Comment by gurkirt** [comment] 2021-09-29 21:59
Can this not be solved by random cropping? Similar to slow-fast where they do random cropping and accordingly resize the boxes.

**Comment by Siyu-C** [comment] 2021-10-12 10:34
Hi @gurkirt , actually we tried a lot of training hyper-parameters (including adding spatial random cropping or optimization settings similar to the SlowFast paper) on the linear baseline, and the current setting is the best one we could find. This repository should support random cropping with [ScaleJitteringRandomCrop](https://github.com/Siyu-C/ACAR-Net/blob/ed5df3d3e53b5df3183149ca130cac57e2c8c64f/datasets/spatial_transforms.py#L354), so feel free to try it. We absolutely welcome any better training setting ;).
